name : cicd-workflow-az-bicep

on:
  push:
    branches:
      - main                                             
      # on fait en sorte que ce pipeline soit déclenché à chaque push vers mon repo github
    paths-ignore:
      - 'README.md'
      - '**/*.md'

env:
  AZURE_WEBAPP_NAME: elyassWebApp   
  NODE_VERSION: '18' 
  AZURE_WEBAPP_PACKAGE_PATH: ./app                                  

permissions:
  contents: read

jobs:
  # CI - ♾️
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Upload node app artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: ./app                                      
                                                         # cette partie du workflow prends le code de notre app node
                                                         # afin de le transformer en artifact (= un paquet réutilisable dans un autre job du pipeline cicd)


  # CD - ♾️
  deploy:
    permissions:
      contents: none
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Development'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

  

    steps:
    - name: Download artifact from build job
      uses: actions/download-artifact@v4
      with:
        name: node-app
        path: ./app

    - name: Azure Login action
      uses: azure/login@v2
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
        enable-AzPSSession: true

    - name: Le run du script de déploiement (deploy.sh)
      run: |
        chmod +x $GITHUB_WORKSPACE/scripts/deploy.sh
        $GITHUB_WORKSPACE/scripts/deploy.sh

    - name: Déploiement de l'app sur la webapp
      uses: azure/webapps-deploy@v3
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
